dataset_config:
  dataset_name: "audiocaption"
  data_dir: ${env.data_root}/datasets/${dataset_config.dataset_name}
  # Caption configs
  captions:
    vocab:
      min_count: 2
      type: pretrained
      embedding_name: glove.6B.300d
      vocab_file: ${data_dir}/vocab.txt
  # Audio configs
  audio:
    sr: 16000
